### ISSUE TITLE
Valve ICD 9 code

### ISSUE THREAD

**Issue by Gomathynathan** [WYATTBENSKEN/multimorbidity#1]
The Elix hauser code identifies  "33394"  as "VALVE" code for ICD 9 , but should only identify if the ICD 9 starts with "394".

**Comment by WYATTBENSKEN** [comment]
Hi. I ran several checks and from what I see 33394 is being correctly coded as neuro. Do you have a specific reproducible example?

**Comment by Gomathynathan** [comment]
Thanks for the clarification!The server i was using had string ver 1.4.0, and str_starts in that version had a bug,and was fixed in later releases. Because of that, 33394 was identified as Valve.

![image](https://github.com/user-attachments/assets/703b1c60-3de2-4690-b689-5f11c90ed83e)
